name: Playit RDP Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest

    steps:
      - name: Download Playit Agent
        run: |
          Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
          echo "Playit downloaded."

      - name: Enable RDP Access
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Set Password for runneradmin
        run: |
          net user runneradmin "YourStrongPassword123"

      - name: Start Playit Tunnel
        env:
          PLAYIT_AUTH_KEY: ${{ secrets.PL }}
        run: |
          echo $env:PLAYIT_AUTH_KEY > playit.toml
          Start-Process "$env:USERPROFILE\playit.exe"

      - name: Keep Alive
        run: |
          Start-Sleep -Seconds 10800
